remove unused configuration and dependency tree logs update build script update license-m-p configuration

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,106 +1,82 @@
-#!/bin/bash -e
-basename=`basename $0`
-dirname=`dirname $0`
-dirname=`cd "$dirname" && pwd`
-cd "$dirname"
+#!/usr/bin/env bash
 
-source build.config
+set -o errexit
+set -o nounset
 
-# load optional config
-if [ -f ./build.rc ]; then
-  source ./build.rc
+# compatibility check
+# shellcheck disable=SC2128
+if [ "$BASH_VERSINFO" -lt 4 ]; then
+  # shellcheck disable=SC2128
+  echo "ERROR: Incompatible Bash detected: $BASH $BASH_VERSINFO $BASH_VERSION"
+  exit 2
 fi
+
+declare -g basename=$(basename "$0")
+declare -g basedir=$(cd "$(dirname "$0")" && pwd)
+declare -g command_default=""
 
 # show message and exit
 function die {
-    echo "$1"
-    exit 1
+  echo "$1"
+  exit 1
 }
 
 # show usage and exit
 function usage {
-  if [[ -z "$1" ]]; then
+  set +o nounset
+  local syntax="$1"
+  set -o nounset
+
+  if [[ -z "$syntax" ]]; then
     echo "usage: $basename <command> [options]"
   else
-    echo "usage: $basename $1"
+    echo "usage: $basename $syntax"
   fi
   exit 2
 }
 
 # run self
 function self {
-    $0 $*
+  $0 "$@"
 }
 
-# run maven
-function mvn {
-    ./mvnw $*
-}
+function main {
+  build_config="$basedir/build-config.bash"
+  # shellcheck source=build-config.bash
+  source "$build_config"
 
-command="$1"; shift
+  build_local_config="$basedir/build-local.bash"
+  if [[ -f "$build_local_config" ]]; then
+    # shellcheck source=build-local.bash
+    source "$build_local_config"
+  fi
 
-# complain if no command is given
-if [ -z "$command" ]; then
+  set +o nounset
+  command="$1"
+  set -o nounset
+
+  set +o errexit
+  shift
+  set -o errexit
+
+  if [[ -z "$command" ]]; then
+    if [[ -n "$command_default" ]]; then
+      self "$command_default"
+    else
+      # complain if no command is given
+      usage
+    fi
+  fi
+
+  # attempt to lookup command function
+  local fn="command_$command"
+  if [[ "$(type -t $fn)" = 'function' ]]; then
+    $fn "$@"
+  else
+    # complain about missing command function
+    echo "Unknown command: $command"
     usage
-fi
+  fi
+}
 
-case "$command" in
-    # change the version of the project
-    change-version)
-        newVersion="$1"
-        if [ -z "$newVersion" ]; then
-            usage "$command <version>"
-        fi
-
-        mvn org.eclipse.tycho:tycho-versions-plugin:1.2.0:set-version \
-          -Dartifacts=${project} \
-          -Dproperties=${project}.version \
-          -DnewVersion="$newVersion"
-        ;;
-
-    # check license headers
-    license-check)
-        mvn -Plicense-check -N $*
-        ;;
-
-    # format license headers
-    license-format)
-        mvn -Plicense-format -N $*
-        ;;
-
-    # release automation
-    release)
-        version="$1"
-        nextVersion="$2"
-        if [ -z "$version" -o -z "$nextVersion" ]; then
-            usage "$command <version> <next-version>"
-        fi
-        releaseTag="release-$version"
-
-        # update version and tag
-        self change-version "$version"
-        git commit -a -m "update version: $version"
-        git tag $releaseTag
-
-        # deploy release
-        mvn -Prelease clean deploy
-
-        # update to next version
-        self change-version "$nextVersion"
-        git commit -a -m "update version: $nextVersion"
-
-        # TODO: push origin (branch + tag)
-        ;;
-
-    *)
-        # attempt to lookup command function
-        fn="command_$command"
-        if [ "$(type -t $fn)" = 'function' ]; then
-          $fn $*
-        else
-          # complain about missing command function
-          echo "Unknown command: $command"
-          usage
-        fi
-        ;;
-esac
+main "$@"
